DROP TABLE IF EXISTS `[prefix]job_categories`;
CREATE TABLE IF NOT EXISTS `[prefix]job_categories` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `parent` int(3) NOT NULL  DEFAULT '0',
  `name` varchar(200) NOT NULL,
  `sorter` tinyint(3) NOT NULL,
  `statistics` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('1', '0', 'Accounting/Finance', '1');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('2', '0', 'Administrative/Clerical', '2');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('3', '0', 'Business/Strategic Management', '3');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('4', '0', 'Building Construction/Skilled Trades', '4');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('5', '0', 'Creative/Design', '5');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('6', '0', 'Customer Support/Client Care', '6');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('7', '0', 'Editorial/Writing', '7');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('8', '0', 'Engineering', '8');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('9', '0', 'Food Services/Hospitality', '9');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('10', '0', 'Human Resources', '10');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('11', '0', 'Installation/Maintenance/Repair', '11');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('12', '0', 'IT/Software Development', '12');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('13', '0', 'Legal', '13');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('14', '0', 'Logistics/Transportation', '14');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('15', '0', 'Marketing/Product', '15');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('16', '0', 'Medical/Health', '16');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('17', '0', 'Production/Operations', '17');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('18', '0', 'Project/Program Management', '18');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('19', '0', 'Quality Assurance/Safety', '19');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('20', '0', 'R_D/Science', '20');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('21', '0', 'Sales/Business Development', '21');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('22', '0', 'Security/Protective Services', '22');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('23', '0', 'Training/Instruction', '23');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('24', '0', 'Other', '24');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('25', '1', 'Accounts Payable/Receivable', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('26', '1', 'Actuarial Analysis', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('27', '1', 'Audit', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('28', '1', 'Bookkeeping/General Ledger', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('29', '1', 'Collections', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('30', '1', 'Corporate Finance', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('31', '1', 'Credit Review/Analysis', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('32', '1', 'Financial Analysis/Research/Reporting', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('33', '1', 'Financial Planning/Advising', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('34', '1', 'Fund Accounting', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('35', '1', 'Investment Management', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('36', '1', 'Policy Underwriting', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('37', '1', 'Risk Management/Compliance', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('38', '1', 'Securities And Commodities Brokerage', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('39', '1', 'Tax Assessment And Collections', '15');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('40', '1', 'Other-General Accounting/Finance', '16');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('41', '1', 'Tax Accounting', '17');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('42', '2', 'Administrative Support', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('43', '2', 'Data Entry/Order Processing', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('44', '2', 'Executive Support', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('45', '2', 'Filing/Records Management', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('46', '2', 'Import/Export Administration', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('47', '2', 'Office Management', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('48', '2', 'Reception/Switchboard', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('49', '2', 'Secretary/Executive Assistant', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('50', '2', 'Other-General Admin/Clerical', '9');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('51', '3', 'Business Analysis/Research', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('52', '3', 'Business Unit Management', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('53', '3', 'Franchise Business Ownership', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('54', '3', 'Head Teacher', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('55', '3', 'Hospital/Clinic Administration', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('56', '3', 'Managerial Consulting', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('57', '3', 'Mergers And Acquisitions', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('58', '3', 'President/Top Executive', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('59', '3', 'Public Health Administration', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('60', '3', 'Sales Support/Assistance', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('61', '3', 'Strategy/Planning', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('62', '3', 'Town/City Planning', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('63', '3', 'Other-General Business/Strategic Mgmt', '13');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('64', '4', 'CAD/Drafting', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('65', '4', 'Carpentry/Framing', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('66', '4', 'Concrete And Masonry', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('67', '4', 'Electrician', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('68', '4', 'Flooring/Tiling/Painting/Wallpapering', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('69', '4', 'Heavy Equipment Operation', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('70', '4', 'HVAC Design And Installation', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('71', '4', 'Ironwork/Metal Fabrication', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('72', '4', 'Plastering', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('73', '4', 'Plumbing/Pipefitting', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('74', '4', 'Roofing', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('75', '4', 'Site Superintendent', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('76', '4', 'Surveying', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('77', '4', 'Other-General Construction/Skilled Trad', '14');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('78', '5', 'Advertising Writing/ Creative', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('79', '5', 'Architecture/Interior Design', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('80', '5', 'Computer Animation/ Multimedia', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('81', '5', 'Creative Direction/Lead', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('82', '5', 'Fashion/ Accessories Design', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('83', '5', 'Graphic Arts/Illustration', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('84', '5', 'Industrial Design', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('85', '5', 'Performer/Artist', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('86', '5', 'Photography And Videography', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('87', '5', 'Web/UI/UX Design', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('88', '5', 'Other-General Creative/Design', '11');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('89', '6', 'Account Management/ Non Commisioned', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('90', '6', 'Bank Teller', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('91', '6', 'Council/Revenue/Benefits', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('92', '6', 'Customer Training', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('93', '6', 'Flight Attendant', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('94', '6', 'Hair Cutting/Styling', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('95', '6', 'Reservations/Ticketing', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('96', '6', 'Retail Customer Service', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('97', '6', 'Technical Customer Service', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('98', '6', 'Other-General Customer Support', '10');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('99', '7', 'Documentation/Technical Writing', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('100', '7', 'Editing/ Proofreading', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('101', '7', 'Journalism', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('102', '7', 'Scriptwriting And Review', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('103', '7', 'Translation/Interpretation', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('104', '7', 'Other-General Editorial/Writing', '6');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('105', '8', 'Aeronautic/Avionic Engineering', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('106', '8', 'Bio Engineering', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('107', '8', 'CAD/Drafting', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('108', '8', 'Chemical Engineering', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('109', '8', 'Civil/ Structural Engineering', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('110', '8', 'Electrical/Electronics Engineering', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('111', '8', 'Energy/Nuclear Engineering', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('112', '8', 'Environmental And Geological Engineering', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('113', '8', 'Industrial/Manufacturing Engineering', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('114', '8', 'Mechanical Engineering', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('115', '8', 'Rf/Wireless Engineering', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('116', '8', 'Systems/Process Engineering', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('117', '8', 'Other-General Engineering', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('118', '8', 'Naval Architecture/Marine Engineering', '14');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('119', '9', 'Other-General Food Services', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('120', '9', 'Wine Steward/Sommelier', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('121', '9', 'Host/Hostess', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('122', '9', 'Guest Services/Concierge', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('123', '9', 'Front Desk/Reception', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('124', '9', 'Food Preparation/Cooking', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('125', '9', 'Food/ Beverage Serving', '7');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('126', '10', 'Other-General HR', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('127', '10', 'Recruiting/Sourcing', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('128', '10', 'Payroll And Benefits Administration', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('129', '10', 'Executive Recruiting', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('130', '10', 'Diversity Management/Eeo/Compliance', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('131', '10', 'Corporate Development And Training', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('132', '10', 'Compensation/Benefits Policy', '7');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('133', '11', 'Computer/Electronics/Telecomm Install', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('134', '11', 'Electrician', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('135', '11', 'Equipment Install/Maintain/Repair', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('136', '11', 'Facilities/Hvac Maintenance', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('137', '11', 'Janitorial/ Cleaning', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('138', '11', 'Landscape Maintenance', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('139', '11', 'Locksmith', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('140', '11', 'Oil Rig & Pipeline Maintenance And Repair', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('141', '11', 'Plumbing/Pipefitting', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('142', '11', 'Vehicle Repair And Maintenance', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('143', '11', 'Other-General IM&R', '11');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('144', '12', 'Web/UI/UX Design', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('145', '12', 'Usability/Information Architecture', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('146', '12', 'Software/System Architecture', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('147', '12', 'IT Project Management', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('148', '12', 'IT Consulting', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('149', '12', 'Enterprise Software Implementation/ Con', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('150', '12', 'Desktop Service And Support', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('151', '12', 'Database Development/Administration', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('152', '12', 'Data Warehousing', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('153', '12', 'Computer/Network Security', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('154', '12', 'Other-General IT/Software Development', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('155', '12', 'Web Mastering', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('156', '12', 'Telecommunications Administration/Techn', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('157', '12', 'Systems Analysis/ IT', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('158', '12', 'Software/Web Development', '15');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('159', '12', 'Network And Server Administration', '16');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('160', '13', 'Barrister', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('161', '13', 'Family Law', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('162', '13', 'Contracts Administration', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('163', '13', 'Criminal Law', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('164', '13', 'Labour/ Employment Law', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('165', '13', 'Patent/IP Law', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('166', '13', 'Tax Law', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('167', '13', 'Paralegal/ Legal Secretary', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('168', '13', 'Real Estate Law', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('169', '13', 'Solicitor', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('170', '13', 'Other-General Legal', '11');
INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('171', '14', 'Train Or Rail Operator', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('172', '14', 'Shipping And Receiving/Warehousing', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('173', '14', 'Piloting: Air And Marine', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('174', '14', 'Merchandise Planning And Buying', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('175', '14', 'Import/Export Administration', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('176', '14', 'Hazardous Materials Handling', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('177', '14', 'Cost Estimating', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('178', '14', 'Car, Van And Bus Driving', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('179', '14', 'Other-General Logistics & Transportation', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('180', '14', 'Vehicle Dispatch/Routing And Scheduling', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('181', '14', 'Truck Driving', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('182', '14', 'Supplier Management/Vendor Management', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('183', '14', 'Purchasing Goods And Services', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('184', '14', 'Messenger/Courier', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('185', '14', 'Inventory Planning And Management', '15');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('186', '14', 'Equipment/Forklift/Crane Operation', '16');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('187', '15', 'Other-General Marketing/Product', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('188', '15', 'Telemarketing', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('189', '15', 'Marketing Production/Traffic', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('190', '15', 'Marketing Communications', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('191', '15', 'Market Research', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('192', '15', 'Direct Marketing/CRM', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('193', '15', 'Brand Marketing', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('194', '15', 'Product Management', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('195', '15', 'Media Planning And Buying', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('196', '15', 'Investor And Public/Media Relations', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('197', '15', 'Events/Promotional Marketing', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('198', '15', 'Copy Writing/Editing', '12');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('199', '16', 'Other-General Medical And Health', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('200', '16', 'Sports Medical Trainer', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('201', '16', 'Public Health Administration', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('202', '16', 'Optical', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('203', '16', 'Nursing', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('204', '16', 'Medical Therapy/Rehab Services', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('205', '16', 'Emt/Paramedic', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('206', '16', 'Dental Practitioner', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('207', '16', 'Veterinary/Animal Care', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('208', '16', 'Social Service', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('209', '16', 'Pharmacy', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('210', '16', 'Nutrition And Diet', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('211', '16', 'Midwifery', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('212', '16', 'Mental Health', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('213', '16', 'Medical Practitioner', '15');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('214', '16', 'Laboratory/Pathology Services', '16');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('215', '16', 'Geriatric/Home Care', '17');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('216', '17', 'Layout/Prepress/Printing//Binding Op', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('217', '17', 'Hazardous Materials Handling', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('218', '17', 'Fishing And Fishing Vessel Operation', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('219', '17', 'Equipment Operations', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('220', '17', 'Audio/Video Broadcast/ Postproduction', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('221', '17', 'Assembly/Assembly Line', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('222', '17', 'Agricultural/Greenhouse Work', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('223', '17', 'Machining Cnc', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('224', '17', 'Metal Fabrication And Welding', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('225', '17', 'Moldmaking/Casting', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('226', '17', 'Operations/Plant Management', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('227', '17', 'Postal Worker', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('228', '17', 'Production/Operations Planning', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('229', '17', 'Sewing And Tailoring', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('230', '17', 'Telecommunications Administration/Techn', '15');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('231', '17', 'Waste Pick Up And Removal', '16');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('232', '17', 'Other-General Production And Operations', '17');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('233', '18', 'Event Planning/Coordination', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('234', '18', 'Housing And Community Development', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('235', '18', 'IT Project Management', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('236', '18', 'Program Management', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('237', '18', 'Project Management', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('238', '18', 'Other-General Project/Program Mgmt', '6');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('239', '19', 'Building/Construction Inspection', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('240', '19', 'Environmental Protection', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('241', '19', 'Fraud Investigation', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('242', '19', 'Iso Certification', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('243', '19', 'Occupational Health And Safety', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('244', '19', 'Production Quality Assurance', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('245', '19', 'Six Sigma/Black Belt/Tqm', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('246', '19', 'Software Quality Assurance', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('247', '19', 'Other-General Qa/Safety/Inspection', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('248', '19', 'Vehicle Inspection', '10');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('249', '20', 'Biological/Chemical Research', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('250', '20', 'Clinical Research', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('251', '20', 'Environmental/Geological Testing', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('252', '20', 'Materials/Physical Research', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('253', '20', 'Mathematical/Statistical Research', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('254', '20', 'New Product R_D', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('255', '20', 'Pharmaceutical Research', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('256', '20', 'Other-General Scientific Research', '8');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('257', '21', 'Account Management/Commisioned', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('258', '21', 'Business Development/New Accounts', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('259', '21', 'Field Sales', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('260', '21', 'Fundraising', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('261', '21', 'Insuranceagent/Broker', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('262', '21', 'International Sales', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('263', '21', 'Media And Advertising Sales', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('264', '21', 'Real Estate Agent/Broker', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('265', '21', 'Retail/Counter Sales And Cashier', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('266', '21', 'Sales Support/Assistance', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('267', '21', 'Securities And Commodities Brokerage', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('268', '21', 'Technical Presales Support/ Technical S', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('269', '21', 'Telesales', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('270', '21', 'Travel Agent/Ticket Sales', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('271', '21', 'Wholesale/Reselling Sales', '15');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('272', '21', 'Other-General Sales/Business Developmen', '16');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('273', '22', 'Customs/Immigration', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('274', '22', 'Firefighting And Rescue', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('275', '22', 'Military', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('276', '22', 'Police Law Enforcement', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('277', '22', 'Prison Officer', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('278', '22', 'Security Guard', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('279', '22', 'Store Security/Loss Prevention', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('280', '22', 'Other-General Security/Protective Service', '8');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('281', '23', 'Academic Research', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('282', '23', 'Classroom Teaching', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('283', '23', 'Continuing/Adult', '3');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('284', '23', 'Corporate Development And Training', '4');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('285', '23', 'Customer Training', '5');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('286', '23', 'Early Childhood Care/ Development', '6');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('287', '23', 'Fitness/ Sports Training/Instruction', '7');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('288', '23', 'Junior/High School', '8');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('289', '23', 'Lecturing', '9');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('290', '23', 'Library Services', '10');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('291', '23', 'Sales Support/Assistance', '11');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('292', '23', 'Special Education', '12');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('293', '23', 'Teaching Support', '13');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('294', '23', 'University', '14');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('295', '23', 'Other-General Training/Instruction', '15');

INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('296', '24', 'Career Fair', '1');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('297', '24', 'Work At Home/Commission Only', '2');INSERT INTO `[prefix]job_categories` (id, parent, name, sorter) VALUES ('298', '24', 'Other', '3');

