<?php
$module['module'] = 'users';
$module['install_name'] = 'Site users management';
$module['install_descr'] = 'Users on site (auth, registration, change profile/delete profile, admin management)';
$module['version'] = '3.02';
$module['files'] = array(
	array('file', 'read', "application/modules/users/controllers/admin_users.php"),
	array('file', 'read', "application/modules/users/controllers/api_users.php"),
	array('file', 'read', "application/modules/users/controllers/users.php"),
	array('file', 'read', "application/modules/users/helpers/users_helper.php"),
	array('file', 'read', "application/modules/users/install/demo_structure_install.sql"),
	array('file', 'read', "application/modules/users/install/module.php"),
	array('file', 'read', "application/modules/users/install/permissions.php"),
	array('file', 'read', "application/modules/users/install/settings.php"),
	array('file', 'read', "application/modules/users/install/structure_deinstall.sql"),
	array('file', 'read', "application/modules/users/install/structure_install.sql"),
	array('file', 'read', "application/modules/users/install/user_fields_data.php"),
	array('file', 'read', "application/modules/users/models/auth_model.php"),
	array('file', 'read', "application/modules/users/models/groups_model.php"),
	array('file', 'read', "application/modules/users/models/users_install_model.php"),
	array('file', 'read', "application/modules/users/models/users_model.php"),
	array('file', 'read', "application/modules/users/models/users_perfect_match_model.php"),
	array('file', 'read', "application/modules/users/models/users_statuses_model.php"),
	array('file', 'read', "application/modules/users/models/users_views_model.php"),
	//array('file', 'read', "application/config/openid.php"),	// Don't delete (openid)
	array('file', 'read', "application/modules/users/js/users-avatar.js"),
	array('file', 'read', "application/modules/users/js/users-input.js"),
	array('file', 'read', "application/modules/users/js/users-list.js"),
	array('file', 'read', "application/modules/users/js/users-select.js"),
	array('file', 'read', "application/modules/users/views/admin/custom_form_fields.tpl"),
	array('file', 'read', "application/modules/users/views/admin/edit_form.tpl"),
	array('file', 'read', "application/modules/users/views/admin/group_edit_form.tpl"),
	array('file', 'read', "application/modules/users/views/admin/groups_list.tpl"),
	array('file', 'read', "application/modules/users/views/admin/helper_admin_home_block.tpl"),
	array('file', 'read', "application/modules/users/views/admin/list.tpl"),
	array('file', 'read', "application/modules/users/views/admin/moder_block.tpl"),
	array('file', 'read', "application/modules/users/views/default/css/style.css"),
	array('file', 'read', "application/modules/users/views/default/account.tpl"),
	array('file', 'read', "application/modules/users/views/default/account_delete_block.tpl"),
	array('file', 'read', "application/modules/users/views/default/account_menu.tpl"),
	array('file', 'read', "application/modules/users/views/default/account_settings.tpl"),
	array('file', 'read', "application/modules/users/views/default/ajax_login_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/ajax_user_avatar.tpl"),
	array('file', 'read', "application/modules/users/views/default/ajax_user_select_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/confirm_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/custom_form_fields.tpl"),
	array('file', 'read', "application/modules/users/views/default/custom_view_fields.tpl"),
	array('file', 'read', "application/modules/users/views/default/dynamic_block_auth_links.tpl"),
	array('file', 'read', "application/modules/users/views/default/dynamic_block_lang_select.tpl"),
	array('file', 'read', "application/modules/users/views/default/dynamic_block_registration_login_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/dynamic_block_users.tpl"),
	array('file', 'read', "application/modules/users/views/default/forgot_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_auth_links.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_featured_users.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_lang_select.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_last_registered.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_login_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_search_field_block.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_search_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_user_input.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_user_select.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_users_carousel.tpl"),
	array('file', 'read', "application/modules/users/views/default/helper_view_user_block.tpl"),
	array('file', 'read', "application/modules/users/views/default/link_add_funds.tpl"),
	array('file', 'read', "application/modules/users/views/default/link_change_password.tpl"),
	array('file', 'read', "application/modules/users/views/default/link_profile.tpl"),
	array('file', 'read', "application/modules/users/views/default/listing.tpl"),
	array('file', 'read', "application/modules/users/views/default/login_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/perfect_match.tpl"),
	array('file', 'read', "application/modules/users/views/default/profile.tpl"),
	array('file', 'read', "application/modules/users/views/default/profile_menu.tpl"),
	array('file', 'read', "application/modules/users/views/default/register.tpl"),
	array('file', 'read', "application/modules/users/views/default/user_form.tpl"),
	array('file', 'read', "application/modules/users/views/default/user_profile.tpl"),
	array('file', 'read', "application/modules/users/views/default/users_list.tpl"),
	array('file', 'read', "application/modules/users/views/default/users_list_block.tpl"),
	array('file', 'read', "application/modules/users/views/default/view.tpl"),
	array('file', 'read', "application/modules/users/views/default/view_my_profile.tpl"),
	array('file', 'read', "application/modules/users/views/default/view_profile_menu.tpl"),
	array('file', 'read', "application/modules/users/views/default/view_users_profile.tpl"),
	array('file', 'read', "application/modules/users/views/default/visits.tpl"),
	array('dir', 'write', "uploads/user-logo"),

	array('dir', 'read', 'application/modules/start/langs'),
);

$module['demo_content'] = array(
	'reinstall' => false, // install demo content on module reinstall
);

$module['dependencies'] = array(
	'start' => array('version'=>'1.03'),
	'menu' => array('version'=>'2.03'),
	'uploads' => array('version'=>'1.03'),
	'moderation' => array('version'=>'1.03'),
	'properties' => array('version'=>'1.03'),
	'countries' => array('version'=>'2.03'),
	'notifications' => array('version'=>'1.04'),
	'linker' => array('version'=>'1.01'),
	'field_editor' =>  array('version'=>'2.01'),
	'cronjob' => array('version' => '1.04')
);

$module['linked_modules'] = array(
	'install' => array(
		'menu'				=> 'install_menu',
		'uploads'			=> 'install_uploads',
		'site_map'			=> 'install_site_map',
		'banners'			=> 'install_banners',
		'linker'			=> 'install_linker',
		'moderation'		=> 'install_moderation',
		'ausers'			=> 'install_ausers',
		'notifications'		=> 'install_notifications',
		'dynamic_blocks'	=> 'install_dynamic_blocks',
		'social_networking' => 'install_social_networking',
		'field_editor'		=> 'install_field_editor',
		'cronjob'			=> 'install_cronjob',
		'services'			=> 'install_services',
		'geomap'			=> 'install_geomap',
		'comments'			=> 'install_comments',
		'spam'				=> 'install_spam',
	),
	'deinstall' => array(
		'menu'				=> 'deinstall_menu',
		'uploads'			=> 'deinstall_uploads',
		'content'			=> 'deinstall_content',
		'site_map'			=> 'deinstall_site_map',
		'banners'			=> 'deinstall_banners',
		'linker'			=> 'deinstall_linker',
		'moderation'		=> 'deinstall_moderation',
		'ausers'			=> 'deinstall_ausers',
		'notifications'		=> 'deinstall_notifications',
		'dynamic_blocks'	=> 'deinstall_dynamic_blocks',
		'social_networking' => 'deinstall_social_networking',
		'field_editor'		=> 'deinstall_field_editor',
		'cronjob'			=> 'deinstall_cronjob',
		'services'			=> 'deinstall_services',
		'geomap'			=> 'deinstall_geomap',
		'comments'			=> 'deinstall_comments',
		'spam'				=> 'deinstall_spam',
	)
);
